services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/seanmicyg12/n8n-docker-render
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: YourStrongPassword123
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: America/Chicago
      - key: DB_SQLITE_VACUUM_ON_STARTUP
        value: "true"